# Generated by Django 4.1 on 2022-08-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=35)),
                ('username', models.CharField(max_length=15)),
            ],
        ),
    ]
