# Generated by Django 4.1 on 2022-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.TextField(max_length=30)),
                ('device_id', models.CharField(max_length=50)),
                ('device_status', models.TextField(max_length=5)),
            ],
        ),
    ]
